spring:
    application:
        name: tccArticle
    data:
        mongodb:
            uri: mongodb://localhost:27017/mongodb-container

    kafka:
        bootstrap-servers: localhost:29092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
    port: 8081

springdoc:
    packagesToScan: com.api.tccArticle
    apiDocs:
        path: /v1/api-docs
    swagger-ui:
        path: /swagger-ui.html

application:
    swagger:
        url: http://localhost:8081